### ISSUE TITLE
Build fails with Ember CLI 1.13.1

### ISSUE THREAD

**Issue by GeoffreyBooth** [ef4/ember-giftwrap#12]
With Ember CLI 0.2.3, with ember-data uninstalled and ember-validations added, I can successfully create an `addons.js` file.

Creating a new Ember CLI project and adding ember-validations and ember-giftwrap, the build fails:

```
 $ ember giftwrap
version: 1.13.1
Build failed.
ENOENT, no such file or directory '/Users/Geoffrey/Sites/sandbox/ember-giftwrapped-app/tmp/broccoli_merge_trees-output_path-nFRBN3ZD.tmp/vendor/ic-ajax/dist/named-amd/main.js'
Error: ENOENT, no such file or directory '/Users/Geoffrey/Sites/sandbox/ember-giftwrapped-app/tmp/broccoli_merge_trees-output_path-nFRBN3ZD.tmp/vendor/ic-ajax/dist/named-amd/main.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at SourceMap.addFile (/Users/Geoffrey/Sites/sandbox/ember-giftwrapped-app/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:67:19)
    at /Users/Geoffrey/Sites/sandbox/ember-giftwrapped-app/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:47:16
    at Array.forEach (native)
    at Class.module.exports.CachingWriter.extend.updateCache (/Users/Geoffrey/Sites/sandbox/ember-giftwrapped-app/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:45:24)
    at /Users/Geoffrey/Sites/sandbox/ember-giftwrapped-app/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/Users/Geoffrey/Sites/sandbox/ember-giftwrapped-app/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/Geoffrey/Sites/sandbox/ember-giftwrapped-app/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:501:17)
```

No luck either with upgrading the earlier project to Ember CLI 1.13.1.

**Comment by GeoffreyBooth** [comment]
Steps to reproduce:

```
ember new test-giftwrap
cd test-giftwrap
ember install ember-giftwrap
ember giftwrap
```

Result:

```
version: 1.13.1
Build failed.
ENOENT, no such file or directory '/Users/Geoffrey/Sites/sandbox/test-giftwrap/tmp/broccoli_merge_trees-output_path-EiEc8Jn7.tmp/vendor/ic-ajax/dist/named-amd/main.js'
Error: ENOENT, no such file or directory '/Users/Geoffrey/Sites/sandbox/test-giftwrap/tmp/broccoli_merge_trees-output_path-EiEc8Jn7.tmp/vendor/ic-ajax/dist/named-amd/main.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at SourceMap.addFile (/Users/Geoffrey/Sites/sandbox/test-giftwrap/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:67:19)
    at /Users/Geoffrey/Sites/sandbox/test-giftwrap/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:47:16
    at Array.forEach (native)
    at Class.module.exports.CachingWriter.extend.updateCache (/Users/Geoffrey/Sites/sandbox/test-giftwrap/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:45:24)
    at /Users/Geoffrey/Sites/sandbox/test-giftwrap/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/Users/Geoffrey/Sites/sandbox/test-giftwrap/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/Geoffrey/Sites/sandbox/test-giftwrap/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:501:17)
```

**Comment by Rrrapture** [comment]
+1

**Comment by blimmer** [comment]
Possibly related to this: https://github.com/rwjblue/ember-cli-ic-ajax/issues/11 ?

Not sure, but also seeing the same behavior described in this issue with Ember CLI 1.13.8.

**Comment by vsymguysung** [comment]
I have the same issue on `Ember CLI 1.3.1`.  Any updates on this?

**Comment by PhilippRoessner** [comment]
same here

**Comment by amakh** [comment]
Any updates?

**Comment by vsymguysung** [comment]
@amakh ,   From the following  `Known Caveats` section, 

> ember giftware always packages all the addons that are installed, there's not currently a way to be more picky. Default ember apps include add ons you may not need (ember-cli-ic-ajax, ember-data, etc), so you'll want to remove them from your package.json if that's the case.

I just removed `ember-cli-ic-ajax` because I don't need it and it just works without the build fail.

**Comment by amakh** [comment]
Thanks @vsymguysung it's working now :)

**Comment by vsymguysung** [comment]
:+1:
