### ISSUE TITLE
Giftwrap Fails with Ember-CLI 2.5.0

### ISSUE THREAD

**Issue by dwolfand** [ef4/ember-giftwrap#13]
Using the following commands using ember-cli 2.5.0

```
ember new testemberapp
cd testemberapp
ember install ember-giftwrap
ember giftwrap
```

Running on node 4.4.3. It fails with the following error:

```
Error: ENOENT: no such file or directory, open '/Users/david/testemberapp/tmp/broccoli_merge_trees-output_path-g8Jpv8om.tmp/bower_components/loader.js/loader.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at SourceMap.addFile (/Users/david/testemberapp/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:69:31)
    at /Users/david/testemberapp/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:47:16
    at Array.forEach (native)
    at Class.module.exports.CachingWriter.extend.updateCache (/Users/david/testemberapp/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:45:24)
    at /Users/david/testemberapp/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/Users/david/testemberapp/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/david/testemberapp/node_modules/ember-giftwrap/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:1048:17)
```

**Comment by jreading** [comment]
You need to add loader to the bower.json file. 

``` javascript
    "loader.js": "ember-cli/loader.js#3.2.0"
```
